spring:
  application:
    name: loanmanagement
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/loanmanagement
    username: root
    password: 9787
  #  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
