spring:
  application:
    name: loanmanagement
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/loanmanagement
    username: postgres
    password: 1234
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update